name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y ripgrep fd-find
          sudo ln -sf $(which fdfind) /usr/local/bin/fd

      - name: Install Socket.dev for supply chain attack protection
        run: npm install -g @socketsecurity/cli

      - name: Install app dependencies
        env:
          SOCKET_SECURITY_API_KEY: ${{ secrets.SOCKET_SECURITY_API_KEY }}
        run: socket npm ci

      - name: Check type/lint/format
        run: npm run check

      - name: Test
        run: npm test

      - name: Build
        run: npm run build
